defaults: &defaults
  api_key: _Vep8xQXpBJ4BEWCJHGd
  s3:
    access_key_id: yourkeyhere
    secret_access_key: yoursecretkeyhere
    bucket: yourbucketnamehere

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
